
# Values used other values
bunnyshellUnique: a1b2c3

# Values used in configmap.yaml
customConfigMap:
  data:
    postgresDb: bunny_books
    postgresHost: db
    postgressPassword: need-to-replace
    postgresUser: postgres

# Values used in configmap.yaml
customService:
  spec:
    ports:
      backend:
        name: "3080"
        port: 3080
        targetPort: 3080
      db:
        name: "5432"
        port: 5432
        targetPort: 5432
      frontend:
        name: "8080"
        port: 8080
        targetPort: 8080

# Values used in oersistentvolumeclaim.yaml
customPvc:
  metadata:
    name: db-data-
    namespace: env-
  spec:
    accessModes:
      RWO: ReadWriteOnce
      RWX: ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: bns-network-sc

# Values used in ingress.yaml
customIngress:
  spec:
    ingressClassName: bns-nginx

# Values used in deployment.yaml
customDeployment:
  backend:
    image:
      repository: aspopescu/backend
      tag: v0.1.0
  frontend:
    image:
      repository: aspopescu/frontend
      tag: v0.1.0