
# Values used other values
bunnyshellUnique: a1b2c3

# Values used in configmap.yaml
customConfigMap:
  data:
    postgresDb: bunny_books
    postgresHost: db
    postgressPassword: need-to-replace
    postgresUser: postgres

# Values used in configmap.yaml
customService:
  spec:
    ports:
      backend:
        name: "3080"
        port: 3080
        targetPort: 3080
      db:
        name: "5432"
        port: 5432
        targetPort: 5432
      frontend:
        name: "8080"
        port: 8080
        targetPort: 8080

# Values used in persistentvolumeclaim.yaml
customPvc:
  metadata:
    name: db-data-
    namespace: env-
  spec:
    accessModes:
      RWO: ReadWriteOnce
      RWX: ReadWriteMany
    resources:
      requests:
        storage: 1Gi
    storageClassName: bns-network-sc

# Values used in ingress.yaml
customIngress:
  spec:
    ingressClassName: bns-nginx
customDomain: bunnyenv.com

# Values used in deployment.yaml
customDeployment:
  backend:
    image:
      repository: aspopescu/bns-nttgdh_1-1-550703666-5ed44c101eba2cf569170d74e1ae131d
      tag: 72a458de1e9dc656e60dabf29543174cffce2cf7
  frontend:
    image:
      repository: aspopescu/bns-nttgdh_1-1-550703666-c08ba4b23aacc59b627197c9b84f91f5
      tag: 72a458de1e9dc656e60dabf29543174cffce2cf7