apiVersion: v1
data:
  FRONTEND_URL: {{ .Values.customConfigMapVariables.frontendUrl }}
  POSTGRES_DB: {{ .Values.customConfigMapVariables.postgresDb }}
  POSTGRES_HOST: {{ .Values.customConfigMapVariables.postgresHost }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMapVariables.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMapVariables.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-backend
---
apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.customConfigMapVariables.postgresDb }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMapVariables.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMapVariables.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-db