apiVersion: v1
data:
  BNS_GIT_BRANCH: master
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: bns-builtin-backend-env-vars
---
apiVersion: v1
data:
  BNS_GIT_BRANCH: master
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: bns-builtin-db-env-vars
---
apiVersion: v1
data:
  BNS_INGRESS_URL_BACKEND_0: backend-qvce4v.bunnyenv.com
  BNS_INGRESS_URL_FRONTEND_0: frontend-qvce4v.bunnyenv.com
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: bns-builtin-env-vars
---
apiVersion: v1
data:
  BNS_GIT_BRANCH: master
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: bns-builtin-frontend-env-vars
---
apiVersion: v1
data:
  FRONTEND_URL: https://frontend-qvce4v.bunnyenv.com
  POSTGRES_DB: bunny_books
  POSTGRES_HOST: db
  POSTGRES_PASSWORD: need-to-replace
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-backend
---
apiVersion: v1
data:
  POSTGRES_DB: bunny_books
  POSTGRES_PASSWORD: need-to-replace
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-db
---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: environment-variables
---
apiVersion: v1
data: {}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: project-variables