apiVersion: v1
data:
  FRONTEND_URL: {{ .Values.customConfigMap.variables.frontendUrl }}
  POSTGRES_DB: {{ .Values.customConfigMap.variables.postgresDb }}
  POSTGRES_HOST: {{ .Values.customConfigMap.variables.postgresHost }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMap.variables.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMap.variables.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-backend
---
apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.customConfigMap.variables.postgresDb }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMap.variables.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMap.variables.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-db