apiVersion: v1
data:
  FRONTEND_URL: {{ .Values.customConfigMap.data.frontendUrl }}
  POSTGRES_DB: {{ .Values.customConfigMap.data.postgresDb }}
  POSTGRES_HOST: {{ .Values.customConfigMap.data.postgresHost }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMap.data.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMap.data.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-backend
---
apiVersion: v1
data:
  POSTGRES_DB: {{ .Values.customConfigMap.data.postgresDb }}
  POSTGRES_PASSWORD: {{ .Values.customConfigMap.data.postgressPassword }}
  POSTGRES_USER: {{ .Values.customConfigMap.data.postgresUser }}
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels: {}
  name: env-file-db