apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    {{- include "demobuc1.albnginx" . | nindent 4 }}
  labels:
    {{- include "demobuc1.ingressLabels" . | nindent 4 }}
  name: {{ .Values.bunnyshellUnique }}-{{ .Values.bunnyshellUnique }}-ingress
spec:
  ingressClassName: {{ .Values.customIngress.spec.ingressClassName }}
  rules:
  - host: backend-{{ .Values.bunnyshellUnique }}.{{ .Values.customDomain }}
    http:
      paths:
      - backend:
          service:
            name: backend
            port:
              number: {{ .Values.customService.spec.ports.backend.port }}
        path: /
        pathType: Prefix
  - host: frontend-{{ .Values.bunnyshellUnique }}.{{ .Values.customDomain }}
    http:
      paths:
      - backend:
          service:
            name: frontend
            port:
              number: {{ .Values.customService.spec.ports.frontend.port }}
        path: /
        pathType: Prefix