apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "demobuc1.IfNotPresent" . | nindent 4 }}
  creationTimestamp: null
  labels:
    {{- include "demobuc1.serviceLabels" . | nindent 4 }} backend
  name: backend
spec:
  ports:
  - name: {{ .Values.customService.spec.ports.backend.name }}
    port: {{ .Values.customService.spec.ports.backend.port }}
    targetPort: {{ .Values.customService.spec.ports.backend.targetPort }}
  selector:
    {{- include "demobuc1.serviceSelector" . | nindent 4 }} backend
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "demobuc1.Always" . | nindent 4 }}
  creationTimestamp: null
  labels:
    labels:
    {{- include "demobuc1.serviceLabels" . | nindent 4 }} db
  name: db
spec:
  ports:
  - name: {{ .Values.customService.spec.ports.db.name }}
    port: {{ .Values.customService.spec.ports.db.port }}
    targetPort: {{ .Values.customService.spec.ports.db.targetPort }}
  selector:
    {{- include "demobuc1.serviceSelector" . | nindent 4 }} db
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  annotations:
    {{- include "demobuc1.IfNotPresent" . | nindent 4 }}
  creationTimestamp: null
  labels:
    labels:
    {{- include "demobuc1.serviceLabels" . | nindent 4 }} frontend
  name: frontend
spec:
  ports:
  - name: {{ .Values.customService.spec.ports.frontend.name }}
    port: {{ .Values.customService.spec.ports.frontend.port }}
    targetPort: {{ .Values.customService.spec.ports.frontend.targetPort }}
  selector:
    {{- include "demobuc1.serviceSelector" . | nindent 4 }} frontend
status:
  loadBalancer: {}